'use client';

import { useEffect, useRef } from 'react';

export default function FireBackground({ theme }) {
    const containerRef = useRef(null);

    useEffect(() => {
        const container = containerRef.current;
        if (!container) return;

        // Clear existing particles if any (React strict mode might double init)
        container.innerHTML = '<!-- Particles generated by JS -->';

        const emberCount = 30; // Fast sparks
        const fogCount = 8;    // Slow deep clouds

        // Helper to create particles
        const createParticle = (type) => {
            const particle = document.createElement('div');
            particle.classList.add('fire-particle', type);

            // Randomize initial properties
            const left = Math.random() * 100; // 0% to 100% width
            const drift = (Math.random() - 0.5) * 300 + 'px'; // Horizontal drift

            // Custom properties based on type
            let duration, delay;

            if (type === 'ember') {
                duration = Math.random() * 3 + 2; // 2-5s (Fast)
                delay = Math.random() * 5;
            } else { // Fog
                duration = Math.random() * 10 + 10; // 10-20s (Slow)
                delay = Math.random() * 10;
            }

            // Apply styles
            particle.style.left = `${left}%`;
            particle.style.setProperty('--drift', drift);
            particle.style.animationDuration = `${duration}s`;
            particle.style.animationDelay = `-${delay}s`; // Negative start

            container.appendChild(particle);

            particle.addEventListener('animationiteration', () => {
                // Randomize position for next loop
                const newLeft = Math.random() * 100;
                const newDrift = (Math.random() - 0.5) * 300 + 'px';
                particle.style.left = `${newLeft}%`;
                particle.style.setProperty('--drift', newDrift);

                // Randomize speed slightly
                if (type === 'ember') {
                    particle.style.animationDuration = `${Math.random() * 3 + 2}s`;
                }
            });
        };

        // Create Embers
        for (let i = 0; i < emberCount; i++) {
            createParticle('ember');
        }
        // Create Fog
        for (let i = 0; i < fogCount; i++) {
            createParticle('fog');
        }

        // Mouse Interaction
        const handleMouseMove = (e) => {
            const x = (e.clientX / window.innerWidth) * 100;
            const y = (e.clientY / window.innerHeight) * 100;
            container.style.setProperty('--mouse-x', `${x}%`);
            container.style.setProperty('--mouse-y', `${y}%`);
        };

        window.addEventListener('mousemove', handleMouseMove);

        return () => {
            window.removeEventListener('mousemove', handleMouseMove);
            // We could clear particles but container gets removed anyway
        };
    }, []);

    // Update theme
    useEffect(() => {
        const container = containerRef.current;
        if (!container) return;

        // Remove old theme classes
        container.classList.remove('theme-f', 'theme-l', 'theme-a', 'theme-m', 'theme-e', 'theme-s');

        // Add new theme class if char is valid
        if (theme) {
            const className = `theme-${theme.toLowerCase()}`;
            container.classList.add(className);
        }
    }, [theme]);

    return <div id="fire-background" className="fire-background" ref={containerRef}></div>;
}
